### ISSUE TITLE
Compilation Error: MOSEK library linking issue

### ISSUE THREAD

**Issue by sunyuan1111** [Zhefan-Xu/time_optimizer#1]
Dear project maintainer,

I'm encountering an error while trying to compile the time_optimizer package. The error occurs during the linking process with the MOSEK library. Here are the details:

## Environment
- Operating System: [Ubuntu 20.04]
- ROS Version: [e.g., ROS Noetic]
- Architecture: [ x86_64]

## Error Message
I'm receiving the following error when running `catkin_make`:
/usr/bin/ld:/home/cwkj/mavros_ws/src/time_optimizer/include/time_optimizer/third_party/lib/x86/libmosek64.so:0: syntax error
collect2: error: ld returned 1 exit status
make[2]: *** [time_optimizer/CMakeFiles/time_optimizer.dir/build.make:631：/home/cwkj/mavros_ws/devel/lib/libtime_optimizer.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:4340：time_optimizer/CMakeFiles/time_optimizer.dir/all] Error 2
make: *** [Makefile:144：all] Error 2
Invoking "make -j2 -l2" failed

Copy

## Steps to Reproduce
1. Cloned the time_optimizer repository
2. Installed dependencies as per the README
3. Ran `catkin_make` in the workspace

## What I've Tried
- Verified the existence of the MOSEK library file
- Checked file permissions
- Ensured the MOSEK version matches my system architecture

## Questions
1. Is there a specific version of MOSEK required for this project?
2. Are there any additional setup steps for MOSEK that aren't mentioned in the README?
3. Could you provide guidance on how to correctly link the MOSEK library in this project?

Any assistance or guidance would be greatly appreciated. Thank you for your time and for maintaining this project.

**Comment by Zhefan-Xu** [comment]
Are you able to build the entire framework? https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy

**Comment by sunyuan1111** [comment]
Sorry that I did not build a complete project, I am a beginner, is it correct that I put this in the src directory of mavros? Could you please give me more detailed instructions on which working plate I should put it in🥺🥺

---- Replied Message ----
| From | Zhefan ***@***.***> |
| Date | 10/13/2024 20:53 |
| To | Zhefan-Xu/time_optimizer ***@***.***> |
| Cc | sunyuan1111 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Zhefan-Xu/time_optimizer] Compilation Error: MOSEK library linking issue (Issue #1) |

Are you able to build the entire framework? https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy

**Comment by sunyuan1111** [comment]
Thank you for your help! I just went to learn ros .This problem was solved by creating a workspace.
mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/
catkin_make

Thank you again for your patience🥰

---- Replied Message ----
| From | Zhefan ***@***.***> |
| Date | 10/13/2024 20:53 |
| To | Zhefan-Xu/time_optimizer ***@***.***> |
| Cc | sunyuan1111 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Zhefan-Xu/time_optimizer] Compilation Error: MOSEK library linking issue (Issue #1) |

Are you able to build the entire framework? https://github.com/Zhefan-Xu/CERLAB-UAV-Autonomy

**Comment by Zhefan-Xu** [comment]
Thanks. Feel free to reopen the issue if you have further questions.
